name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PORT: 3000
      NODE_ENV: development
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_HOST: localhost
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_PORT: 5432
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm test

      - name: Build Docker backend image
        run: docker build -t $DOCKER_USERNAME/webclassroom-backend:latest ./src/backend

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Push Docker image
        run: docker push $DOCKER_USERNAME/webclassroombackend:latest